insert into Courses (course_id, name, credit_hours, text_book) values (1, 'Introduction to Quantum Mechanics', 3, 'Principles of Quantum Mechanics by R. Shankar');
insert into Courses (course_id, name, credit_hours, text_book) values (2, 'Comparative Literature: Global Perspectives', 2, 'Hacking: The Art of Exploitation by Jon Erickson');
insert into Courses (course_id, name, credit_hours, text_book) values (3, 'Cybersecurity Fundamentals', 2, 'Data Science for Social Good: Building a Better World with AI by Emmanuel Ameisen');
insert into Courses (course_id, name, credit_hours, text_book) values (4, 'Data Science for Social Good', 2, 'Walkable City: How Downtown Can Save America One Step at a Time by Jeff Speck');
insert into Courses (course_id, name, credit_hours, text_book) values (5, 'Sustainable Urban Planning', 3, 'Nudge: Improving Decisions About Health Wealth and Happiness by Richard H. Thaler and Cass R. Sunstein');
insert into Courses (course_id, name, credit_hours, text_book) values (6, 'Behavioral Economics and Decision Making', 4, 'Robot Ethics: The Ethical and Social Implications of Robotics by Patrick Lin');
insert into Courses (course_id, name, credit_hours, text_book) values (7, 'Artificial Intelligence Ethics', 5, 'Astrophysics for People in a Hurry by Neil deGrasse Tyson');
insert into Courses (course_id, name, credit_hours, text_book) values (8, 'Advanced Astrophysics', 3, 'The Environment and International Relations by Kate O''Neill');
insert into Courses (course_id, name, credit_hours, text_book) values (9, 'Environmental Policy and Governance', 2, 'Marketing 4.0: Moving from Traditional to Digital by Philip Kotler');
insert into Courses (course_id, name, credit_hours, text_book) values (10, 'Digital Marketing Strategies', 4, 'Ways of Seeing by John Berger');
insert into Courses (course_id, name, credit_hours, text_book) values (11, 'Contemporary Art and Society', 5, 'Art & Today by Eleanor Heartney');
insert into Courses (course_id, name, credit_hours, text_book) values (12, 'Biomedical Engineering Innovations', 2, 'Bioengineering Fundamentals by S. Ghista');
insert into Courses (course_id, name, credit_hours, text_book) values (13, 'International Human Rights Law', 5, 'The International Human Rights Movement: A History by Aryeh Neier');
insert into Courses (course_id, name, credit_hours, text_book) values (14, 'Financial Derivatives and Risk Management', 5, 'Options Futures and Other Derivatives by John C. Hull');
insert into Courses (course_id, name, credit_hours, text_book) values (15, 'Neurobiology of Addiction', 4, 'The Biology of Desire: Why Addiction Is Not a Disease by Marc Lewis');
insert into Courses (course_id, name, credit_hours, text_book) values (16, 'Creative Writing Workshop', 3, 'On Writing: A Memoir of the Craft by Stephen King');
insert into Courses (course_id, name, credit_hours, text_book) values (17, 'Game Design and Development', 2, 'The Art of Game Design: A Book of Lenses by Jesse Schell');
insert into Courses (course_id, name, credit_hours, text_book) values (18, 'History of Ancient Civilizations', 4, 'The Ancient Near East: A Very Short Introduction by Amanda H. Podany');
insert into Courses (course_id, name, credit_hours, text_book) values (19, 'Entrepreneurship in the Digital Age', 3, 'The Lean Startup: How Today''s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses by Eric Ries');
insert into Courses (course_id, name, credit_hours, text_book) values (20, 'Advanced Topics in Cryptography', 2, 'Cryptography and Network Security: Principles and Practice by William Stallings');
insert into Courses (course_id, name, credit_hours, text_book) values (21, 'Gender Studies: Intersectional Perspectives', 5, 'Intersectionality by Patricia Hill Collins and Sirma Bilge');
insert into Courses (course_id, name, credit_hours, text_book) values (22, 'Renewable Energy Technologies', 3, 'Renewable Energy: Power for a Sustainable Future by Godfrey Boyle');
insert into Courses (course_id, name, credit_hours, text_book) values (23, 'Public Health Policy Analysis', 4, 'Introduction to Public Health by Mary-Jane Schneider');
insert into Courses (course_id, name, credit_hours, text_book) values (24, 'Comparative Politics of the Middle East', 3, 'The Middle East: A History by William Ochsenwald and Sydney Nettleton Fisher');
insert into Courses (course_id, name, credit_hours, text_book) values (25, 'Advanced Organic Chemistry', 2, 'Organic Chemistry by Jonathan Clayden Nick Greeves and Stuart Warren');
insert into Courses (course_id, name, credit_hours, text_book) values (26, 'Cognitive Neuroscience', 3, 'Cognitive Neuroscience: The Biology of the Mind by Michael Gazzaniga and Richard B. Ivry');
insert into Courses (course_id, name, credit_hours, text_book) values (27, 'Big Data Analytics in Healthcare', 2, 'Big Data Health Law and Bioethics by I. Glenn Cohen et al.');
insert into Courses (course_id, name, credit_hours, text_book) values (28, 'Global Marketing Strategy', 5, 'Global Marketing Management by Warren J. Keegan and Mark C. Green');
insert into Courses (course_id, name, credit_hours, text_book) values (29, 'Contemporary Issues in Philosophy', 2, 'Contemporary Debates in Philosophy of Mind edited by Brian P. McLaughlin and Jonathan Cohen');
insert into Courses (course_id, name, credit_hours, text_book) values (30, 'Space Exploration and Colonization', 4, 'The Future of Humanity: Terraforming Mars Interstellar Travel Immortality and Our Destiny Beyond Earth by Michio Kaku');
